### ISSUE TITLE
llvm::GBZ80RegisterInfo::eliminateFrameIndex is not implemented

### ISSUE THREAD

**Issue by luqsthunder** [euclio/llvm-gbz80#1]
Hi everybody.
I got some errors trying to compile using archlinux and clang 3.8.0.

First I got these errors:  
undefined reference to `llvm::GBZ80GenInstrInfo::~GBZ80GenInstrInfo()' on file GBZ80TargetMachine.cpp
I've corrected them by adding this to a file: 
# define GET_REGINFO_TARGET_DESC
# include "GBZ80GenRegisterInfo.inc"

and now I got: undefined reference to `llvm::GBZ80RegisterInfo::eliminateFrameIndex
on the same file. Also I've checked other targets and they have this implemented as well,  so it's not automatically generated.
Is there any workaround?

**Comment by euclio** [comment]
Hi @luqsthunder, I started this fork as a project in college and didn't finish it. It's essentially abandoned.
